//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaret
{
    using System;
    using System.Collections.Generic;
    
    public partial class ürün
    {
        public string Ad { get; set; }
        public string Fiyat { get; set; }
        public string Resim { get; set; }
        public int MarkaID { get; set; }
        public int KategoriID { get; set; }
        public int ürünID { get; set; }
        public Nullable<int> Stok { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Marka Marka { get; set; }
    }
}
